#!/usr/bin/env python3
"""Renders Classic's whispering announcer into Game/js/voice-data.js.

Each phrase is spoken by the Kathleen Piper voice (a female U.S. English voice trained on a CC0 dataset), then
turned into a whisper: linear prediction keeps the shape of the mouth (the formants) but the voiced buzz is replaced
by breath noise, low rumble is cut and the air on top lifted. The clips are encoded as small MP3s and embedded as
base64, so the app needs no files and no network, and sounds the same everywhere.

Needs: pip install piper-tts numpy scipy lameenc, and the voice from
https://github.com/rhasspy/piper/releases/download/v0.0.2/voice-en-us-kathleen-low.tar.gz

    python3 Lull/scripts/make-voice.py path/to/en-us-kathleen-low.onnx
"""
import base64, io, os, sys, wave
import numpy as np
from scipy.signal import lfilter, butter
from piper import PiperVoice
from piper.config import SynthesisConfig
import lameenc

PHRASES = {
    'single': 'single', 'double': 'double', 'triple': 'triple', 'tetris': 'tetris',
    'tspin': 'tee spin', 'mini': 'mini', 'b2b': 'back to back', 'perfect': 'perfect clear',
    'levelup': 'next level', 'gameover': 'game over',
}


def speak(voice, text):
    buf = io.BytesIO()
    with wave.open(buf, 'wb') as w:
        voice.synthesize_wav(text, w, syn_config=SynthesisConfig(length_scale=1.15, noise_scale=0.5, noise_w_scale=0.6))
    buf.seek(0)
    with wave.open(buf, 'rb') as w:
        sr = w.getframerate()
        x = np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16).astype(np.float64) / 32768.0
    return x, sr


def lpc(frame, order):
    r = np.correlate(frame, frame, 'full')[len(frame) - 1:len(frame) + order]
    if r[0] <= 1e-9:
        return np.zeros(order + 1), 0.0
    r[0] *= 1.0001
    a = np.zeros(order + 1); a[0] = 1.0
    e = r[0]
    for i in range(1, order + 1):
        k = -(r[i] + np.dot(a[1:i], r[i - 1:0:-1])) / e
        a[1:i] = a[1:i] + k * a[i - 1:0:-1]
        a[i] = k
        e *= (1 - k * k)
    return a, max(e, 0.0)


def whisper(x, sr, seed):
    rng = np.random.default_rng(seed)
    n, hop = int(0.025 * sr), int(0.008 * sr)
    win = np.hanning(n)
    out = np.zeros(len(x) + n)
    norm = np.zeros(len(x) + n)
    pre = lfilter([1, -0.9], [1], x)  # pre-emphasis, so the high formants are modelled too
    for s in range(0, len(x) - n, hop):
        f = pre[s:s + n] * win
        a, e = lpc(f, 18)
        if e <= 0:
            continue
        noise = rng.standard_normal(n) * np.sqrt(e / n)
        y = lfilter([1], a, noise) * win
        out[s:s + n] += y
        norm[s:s + n] += win ** 2
    out = out[:len(x)] / np.maximum(norm[:len(x)], 1e-3)
    out = lfilter([1], [1, -0.9], out)  # undo the pre-emphasis
    b, a = butter(2, 350 / (sr / 2), 'high')
    out = lfilter(b, a, out)
    # A little air: a gentle lift around 3-6 kHz.
    b, a = butter(2, [2800 / (sr / 2), min(0.95, 6500 / (sr / 2))], 'band')
    out = out + 0.35 * lfilter(b, a, out)
    # Trim silence, fade the edges, normalise.
    env = np.convolve(np.abs(out), np.ones(int(0.02 * sr)) / int(0.02 * sr), 'same')
    idx = np.where(env > env.max() * 0.012)[0]
    if len(idx):
        out = out[max(0, idx[0] - int(0.03 * sr)):min(len(out), idx[-1] + int(0.15 * sr))]
    fade = int(0.012 * sr)
    out[:fade] *= np.linspace(0, 1, fade)
    out[-fade:] *= np.linspace(1, 0, fade)
    return out / (np.abs(out).max() + 1e-9) * 0.7


def mp3(x, sr):
    enc = lameenc.Encoder()
    enc.set_bit_rate(40); enc.set_in_sample_rate(sr); enc.set_channels(1); enc.set_quality(2)
    pcm = (np.clip(x, -1, 1) * 32767).astype(np.int16).tobytes()
    return enc.encode(pcm) + enc.flush()


def main():
    onnx = sys.argv[1]
    voice = PiperVoice.load(onnx, config_path=onnx + '.json')
    clips = {}
    for i, (key, text) in enumerate(PHRASES.items()):
        x, sr = speak(voice, text)
        clips[key] = base64.b64encode(mp3(whisper(x, sr, 7 + i), sr)).decode('ascii')
        print(key, len(clips[key]) * 3 // 4, 'bytes')
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, '..', 'Game', 'js', 'voice-data.js')
    with open(path, 'w') as f:
        f.write('// Generated by scripts/make-voice.py: the Classic announcer, whispered (Kathleen Piper voice, CC0 data).\n')
        f.write('(function (root) {\n  const L = (root.Lull = root.Lull || {});\n  L.VOICE_CLIPS = {\n')
        for key, b64 in clips.items():
            f.write('    %s: \'%s\',\n' % (key, b64))
        f.write('  };\n})(typeof globalThis !== \'undefined\' ? globalThis : this);\n')
    print('wrote', os.path.normpath(path))


if __name__ == '__main__':
    main()
