#!/usr/bin/env node
// Builds js/minsize.js: the smallest board each of Shapes' sources is dealt on (js/shapes.js, minSize), measured. From
// the geometric floor (w ≥ max(4, M+2), h ≥ max(8, L+4): M the largest short side of its shapes, L the longest), the
// size grows, a column or a row at a time (whichever is the smaller share of Standard's 10 × 20), until the plain bot
// (scripts/shapes-bot.cjs) lives at least as long, as the median of 20 boards, as it does with Normal shapes on the
// smallest board they have (4 × 8): no set ends sooner at its minimum than the seven do at theirs. A source: a preset
// (tiny, frantic, pentominoes, big), a group of n blocks ('g<n>'; doubled: 'g<n>B') or clusters of k blocks ('c<k>',
// 'c<k>B', each as hard as all k).
//   node Lull/scripts/minsize.cjs            writes Lull/Game/js/minsize.js
//   node Lull/scripts/minsize.cjs --check    measures again and compares (exit 1 when they differ)
'use strict';
const fs = require('fs');
const path = require('path');
const load = require('./load.cjs');
const Bot = require('./shapes-bot.cjs');

const OUT = path.join(__dirname, '..', 'Game', 'js', 'minsize.js');
const SEEDS = Array.from({ length: 20 }, (_, i) => i + 1);
const median = (a) => a.slice().sort((x, y) => x - y)[a.length >> 1];

/** Every source measured, with the recipe that deals it alone. */
function cases() {
  const out = [['tiny', { preset: 'tiny' }], ['frantic', { preset: 'frantic' }], ['pentominoes', { preset: 'pentominoes' }], ['big', { preset: 'big' }]];
  for (let n = 1; n <= 12; n++) for (const big of ['off', 'all']) out.push(['g' + n + (big === 'all' ? 'B' : ''), { preset: 'custom', custom: { groups: [{ n, weight: 'even' }], big } }]);
  for (let k = 2; k <= 8; k++) for (const big of ['off', 'all']) out.push(['c' + k + (big === 'all' ? 'B' : ''), { preset: 'custom', custom: { groups: [], clusters: { min: k, max: k, weight: 'even' }, big } }]);
  return out;
}

/** The median life (pieces, at most cap) of a set on a w × h board over the seeds. */
function lifeAt(L, shapes, w, h, cap) { return median(SEEDS.map((s) => Bot.life(L.Game, { shapes }, w, h, s, cap))); }
/** The least life a minimum must give: Normal shapes' median on 4 × 8. */
function target(L) { return lifeAt(L, { preset: 'normal' }, 4, 8, 1000); }

/** The measured minimum of one source: [w, h]. */
function measure(L, shapes, T) {
  const floor = { w: 4, h: 8 };
  for (const s of L.Shapes.sources(shapes)) { floor.w = Math.max(floor.w, s.M + 2); floor.h = Math.max(floor.h, s.L + 4); }
  let w = Math.min(20, floor.w), h = Math.min(40, floor.h);
  let life;
  while ((life = lifeAt(L, shapes, w, h, T)) < T && (w < 20 || h < 40)) {
    if ((w / 10 <= h / 20 && w < 20) || h >= 40) w++; else h++;
  }
  // Short of it even on the largest board (Big shapes of 9 blocks and more): dealt only there.
  return life >= T ? [w, h] : [w, h, life];
}

function source(mins, T) {
  return [
    '// Lull — the smallest board each of the board recipe\'s shape sources is dealt on (js/shapes.js, minSize), generated by',
    '// scripts/minsize.cjs: do not edit. By source ([w, h]): where the plain bot lives, as the median of 20 boards, at',
    '// least as long as it does with Normal shapes on 4 × 8 (' + T + ' pieces); [20, 40, life] a source short of it even on',
    '// the largest board (dealt only there).',
    '(function (root) {',
    "  'use strict';",
    '  const L = (root.Lull = root.Lull || {});',
    '  L.ShapeMins = {',
    ...Object.entries(mins).map(([k, m]) => '    ' + k + ': [' + m.join(', ') + '],'),
    '  };',
    '  L.ShapeMins.life = ' + T + ';',
    '})(typeof globalThis !== \'undefined\' ? globalThis : this);',
    '',
  ].join('\n');
}

if (require.main === module) {
  // Measured without a table of minimums (each source's floor is its geometry alone).
  const L = load(['util.js', 'pieces.js', 'board.js', 'recipe.js', 'engine.js', 'polytable.js', 'shapes.js']);
  const t0 = Date.now(), T = target(L), mins = {};
  console.log('  Normal on 4 x 8 lives ' + T + ' pieces (median)');
  for (const [key, shapes] of cases()) {
    mins[key] = measure(L, shapes, T);
    console.log('  ' + key.padEnd(12) + mins[key].slice(0, 2).join(' x ') + (mins[key][2] != null ? ' (lives ' + mins[key][2] + ')' : '') + '  (' + ((Date.now() - t0) / 1000).toFixed(1) + ' s)');
  }
  const src = source(mins, T);
  if (process.argv.includes('--check')) {
    const same = fs.readFileSync(OUT, 'utf8') === src;
    console.log(same ? 'minsize: identical' : 'minsize: DIFFERS');
    process.exit(same ? 0 : 1);
  }
  fs.writeFileSync(OUT, src);
  console.log('wrote ' + path.relative(process.cwd(), OUT) + ' (' + ((Date.now() - t0) / 1000).toFixed(1) + ' s)');
}
module.exports = { cases, lifeAt, target, measure, SEEDS, median };
