#!/usr/bin/env node
// Builds js/polytable.js, the table Shapes draws groups of 1 to 12 blocks through (js/shapes.js): for each n, the depth
// d of the enumeration tree its counts are kept at (8 for up to 10 blocks, 9 for 11 and 12: about 55 KB, 11 KB gzipped)
// and, for each node there in enumeration order, how many one-sided shapes of n blocks with no sealed hole lie below it.
// The enumerator is js/shapes.js's own, so the table and the draws always agree.
//   node Lull/scripts/polytable.cjs            writes Lull/Game/js/polytable.js
//   node Lull/scripts/polytable.cjs --check    builds it and compares (exit 1 when they differ)
'use strict';
const fs = require('fs');
const path = require('path');
const load = require('./load.cjs');

const OUT = path.join(__dirname, '..', 'Game', 'js', 'polytable.js');
const depthOf = (n) => Math.min(n <= 10 ? 8 : 9, n - 1);

/** { n: { d, counts: Int32Array, total } } for n = 1 … max, from a full enumeration. */
function build(L, max) {
  const out = {};
  for (let n = 1; n <= max; n++) {
    const d = depthOf(n), E = L.Shapes.enumFor(n), counts = [];
    let total = 0;
    if (d < 1) { E.run(-1, -1, null, null, () => { total++; return false; }); out[n] = { d, counts: [], total }; continue; }
    E.run(-1, d, null, () => { counts.push(0); return true; }, () => { counts[counts.length - 1]++; total++; return false; });
    out[n] = { d, counts, total };
  }
  return out;
}

function source(L, tab) {
  const lines = Object.entries(tab).map(([n, t]) => '    ' + n + ": { d: " + t.d + ", c: '" + L.Shapes.encode(t.counts) + "' },");
  return [
    '// Lull — the sampling table for the board recipe\'s shape groups (js/shapes.js), generated by scripts/polytable.cjs:',
    '// do not edit. For each group of n blocks, the depth d of the enumeration tree its counts are kept at, and c, for each',
    '// node there in enumeration order, how many one-sided shapes with no sealed hole lie below it (base 36, a run of',
    '// zeros as _ and its length).',
    '(function (root) {',
    "  'use strict';",
    '  const L = (root.Lull = root.Lull || {});',
    '  L.PolyTable = {',
    ...lines,
    '  };',
    '})(typeof globalThis !== \'undefined\' ? globalThis : this);',
    '',
  ].join('\n');
}

if (require.main === module) {
  const L = load(['util.js', 'pieces.js', 'board.js', 'recipe.js', 'shapes.js']);
  const t0 = Date.now();
  const tab = build(L, 12);
  for (const [n, t] of Object.entries(tab)) console.log('  n=' + n + ' d=' + t.d + ' nodes=' + t.counts.length + ' shapes=' + t.total);
  const src = source(L, tab);
  if (process.argv.includes('--check')) {
    const same = fs.readFileSync(OUT, 'utf8') === src;
    console.log(same ? 'polytable: identical' : 'polytable: DIFFERS');
    process.exit(same ? 0 : 1);
  }
  fs.writeFileSync(OUT, src);
  console.log('wrote ' + path.relative(process.cwd(), OUT) + ' (' + src.length + ' bytes, ' + (Date.now() - t0) + ' ms)');
}
module.exports = { build, source, depthOf };
