#!/usr/bin/env node
// Lull — builds Game/js/voice-data.js, Classic's announcer, from a folder of whispered clips generated with ElevenLabs
// (text to speech; voice "Annie - Whispering British Girl", model eleven_v4, a real whisper; MP3), one file a line:
//   single, double, triple, quad, twist, twist_single, twist_double, streak, spotless, levelup, gameover (.mp3)
//
//   node Lull/scripts/voice-clips.cjs <folder of mp3s>
//
// Each clip is embedded as base64 (L.VOICE_CLIPS) with what the Announcer (js/audio.js) needs to play it well
// (L.VOICE_META): where the speech starts and ends (seconds into the file, measured by decoding it in Playwright's
// Chromium, the same decoder the game uses), and a loudness trim (dB). The trim is fitted in two steps: first so the
// raw speech sits at TARGET (a gated RMS), then, with the clips rendered through the Announcer's real chain
// (OfflineAudioContext, at the default volume: a high-pass, her level and a limiter that should never touch her),
// nudged until every call comes out at the same level. Needs Playwright, like browser-test.cjs.
'use strict';
const fs = require('fs');
const path = require('path');
let chromium;
try { ({ chromium } = require('playwright')); } catch (e) {
  try { ({ chromium } = require(path.join(process.execPath, '..', '..', 'lib', 'node_modules', 'playwright'))); } catch (e2) {
    console.error('Playwright is not installed.');
    process.exit(1);
  }
}
const { SRC } = require('./voice-measure.cjs');

const KEYS = ['single', 'double', 'triple', 'quad', 'twist', 'twist_single', 'twist_double', 'streak', 'spotless', 'levelup', 'gameover'];
const SAYS = { single: 'single', double: 'double', triple: 'triple', quad: 'quad', twist: 'twist', twist_single: 'twist single', twist_double: 'twist double',
  streak: 'streak', spotless: 'spotless', levelup: 'level up', gameover: 'game over' };
/** The raw speech level every clip is first trimmed to (dB, gated RMS). */
const TARGET = -32;
const OUT = path.join(__dirname, '..', 'Game', 'js', 'voice-data.js');
const PAGE = 'file://' + path.join(__dirname, '..', 'Game', 'index.html');
const r3 = (x) => Math.round(x * 1000) / 1000;
const r2 = (x) => Math.round(x * 100) / 100;

function write(clips, meta) {
  const lines = [
    '// Generated by scripts/voice-clips.cjs; do not edit by hand. Classic\'s announcer: whispered clips generated with',
    '// ElevenLabs (text to speech; voice "Annie - Whispering British Girl", model eleven_v4) for Lull. Their use is governed by',
    '// the terms of the ElevenLabs plan they were made on. VOICE_META: where her speech starts and ends in each clip',
    '// (seconds) and the loudness trim that brings every call to one level (dB); js/audio.js (Announcer) plays only that.',
    '(function (root) {',
    '  const L = (root.Lull = root.Lull || {});',
    '  L.VOICE_META = {',
    ...KEYS.map((k) => '    ' + k + ': ' + JSON.stringify(meta[k]).replace(/"(\w+)":/g, '$1: ').replace(/,/g, ', ').replace(/^\{/, '{ ').replace(/\}$/, ' }') + ', // "' + SAYS[k] + '"'),
    '  };',
    '  L.VOICE_CLIPS = {',
    ...KEYS.map((k) => '    ' + k + ": '" + clips[k] + "',"),
    '  };',
    '})(typeof globalThis !== \'undefined\' ? globalThis : this);',
    '',
  ];
  fs.writeFileSync(OUT, lines.join('\n'));
}

(async () => {
  const dir = process.argv[2];
  if (!dir) { console.error('usage: node Lull/scripts/voice-clips.cjs <folder of mp3s>'); process.exit(2); }
  const clips = {};
  for (const k of KEYS) {
    const f = path.join(dir, k + '.mp3');
    if (!fs.existsSync(f)) { console.error('missing ' + f); process.exit(2); }
    clips[k] = fs.readFileSync(f).toString('base64');
  }
  const browser = await chromium.launch(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {});
  try {
    // 1. The raw clips: where the speech is, how loud it is, and the trim to TARGET.
    const page = await browser.newPage();
    await page.goto('about:blank');
    await page.evaluate(SRC);
    const raw = await page.evaluate(async ({ clips, KEYS }) => {
      const out = {};
      for (const k of KEYS) {
        const bin = atob(clips[k]), bytes = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
        const ctx = new OfflineAudioContext(1, 44100, 44100);
        const buf = await ctx.decodeAudioData(bytes.buffer);
        const x = buf.getChannelData(0), M = window.VoiceMeasure, sp = M.span(x, buf.sampleRate);
        out[k] = { dur: buf.duration, start: sp.start, end: sp.end, loud: M.loudness(x, buf.sampleRate, sp.start, sp.end), peak: M.peak(x) };
      }
      return out;
    }, { clips, KEYS });
    const meta = {};
    for (const k of KEYS) meta[k] = { start: r3(raw[k].start), end: r3(raw[k].end), gain: r2(TARGET - raw[k].loud) };
    write(clips, meta);

    // 2. Through the Announcer's chain: every call rendered at the default volume, and the trims nudged to one level.
    const game = await browser.newPage();
    await game.goto(PAGE);
    await game.waitForTimeout(400);
    await game.evaluate(SRC);
    let spread = 0;
    for (let pass = 0; pass < 10; pass++) {
      const got = await game.evaluate(async ({ meta, KEYS }) => {
        const S = Lull.Sound, A = Lull.Announcer, keep = A.volume, M = window.VoiceMeasure;
        Lull.VOICE_META = meta;
        A.setVolume(Lull.defaultState().settings.announcerVolume); // as most will hear her: the default level
        const out = {};
        try {
          for (const k of KEYS) {
            const buf = await A.decode(k);
            A.input = null;
            const dur = A.span(k, buf).dur;
            const r = await S.offline(dur + 0.3, () => { A.clip(k, buf, 0.05); });
            out[k] = M.loudness(r.getChannelData(0), r.sampleRate, 0.05, 0.05 + dur);
          }
        } finally { A.input = null; A.setVolume(keep); }
        return out;
      }, { meta, KEYS });
      const vals = KEYS.map((k) => got[k]).sort((a, b) => a - b), mid = vals[Math.floor(vals.length / 2)];
      spread = vals[vals.length - 1] - vals[0];
      console.log('pass ' + (pass + 1) + ': rendered loudness spread ' + spread.toFixed(2) + ' dB');
      if (spread < 0.4) break;
      // The chain is linear below its limiter, so a step in comes out the same: step by the difference, at most 4 dB a pass.
      for (const k of KEYS) meta[k].gain = r2(meta[k].gain + Math.max(-4, Math.min(4, mid - got[k])));
    }
    write(clips, meta);
    console.log('clip            file   speech        raw loud  raw peak  trim');
    for (const k of KEYS) {
      const r = raw[k];
      console.log(k.padEnd(14) + (r.dur.toFixed(2) + ' s').padStart(8) + ('  ' + meta[k].start.toFixed(2) + '–' + meta[k].end.toFixed(2) + ' s').padEnd(15) +
        (r.loud.toFixed(1) + ' dB').padStart(9) + (r.peak.toFixed(1) + ' dB').padStart(10) + ((meta[k].gain >= 0 ? '+' : '') + meta[k].gain.toFixed(1) + ' dB').padStart(9));
    }
    console.log('wrote ' + path.relative(process.cwd(), OUT) + ' (' + Math.round(fs.statSync(OUT).size / 1024) + ' KB)');
  } finally { await browser.close(); }
})().catch((e) => { console.error(e); process.exit(1); });
