// Lull — the smallest board each of the board recipe's shape sources is dealt on (js/shapes.js, minSize), generated by
// scripts/minsize.cjs: do not edit. By source ([w, h]): where the plain bot lives, as the median of 20 boards, at
// least as long as it does with Normal shapes on 4 × 8 (16 pieces); [20, 40, life] a source short of it even on
// the largest board (dealt only there).
(function (root) {
  'use strict';
  const L = (root.Lull = root.Lull || {});
  L.ShapeMins = {
    tiny: [4, 8],
    frantic: [5, 9],
    pentominoes: [6, 10],
    big: [8, 16],
    g1: [4, 8],
    g1B: [4, 8],
    g2: [4, 8],
    g2B: [4, 8],
    g3: [4, 8],
    g3B: [6, 10],
    g4: [4, 8],
    g4B: [8, 16],
    g5: [6, 10],
    g5B: [12, 24],
    g6: [7, 14],
    g6B: [16, 30],
    g7: [9, 16],
    g7B: [18, 34],
    g8: [10, 18],
    g8B: [20, 40],
    g9: [11, 20],
    g9B: [20, 40, 13],
    g10: [12, 22],
    g10B: [20, 40, 11],
    g11: [13, 25],
    g11B: [20, 40, 10],
    g12: [13, 26],
    g12B: [20, 40, 8],
    c2: [5, 8],
    c2B: [8, 10],
    c3: [5, 9],
    c3B: [10, 19],
    c4: [6, 12],
    c4B: [14, 26],
    c5: [8, 14],
    c5B: [16, 30],
    c6: [9, 16],
    c6B: [18, 34],
    c7: [10, 18],
    c7B: [20, 38],
    c8: [11, 20],
    c8B: [20, 40, 15],
  };
  L.ShapeMins.life = 16;
})(typeof globalThis !== 'undefined' ? globalThis : this);
