// Lull — the Guide's cards (js/patterns.js reads them; js/patternsview.js draws them): for each shape, four small boards
// as pictures, rows top first ('#' and lowercase letters the stack, an uppercase letter the piece being set, '.' empty),
// each with a caption of four words at most. The marks on them are never drawn here: the detector finds them, and
// scripts/patterns-unit.cjs holds every picture to its caption (the shape is there, made, not made, undone).
//   what, happens, avoid, recover: { pic, cap, ctx }   ctx: the Next, Hold, the speed or the keys the board needs
//   by: what recovering does ('cleared', 'cleared:<id>', 'dig', 'lines', 'room', 'none', or a shape's id)
(function (root) {
  'use strict';
  const L = (root.Lull = root.Lull || {});
  const P = L.Patterns;
  if (!P) return;
  const C = (pic, cap, ctx) => ({ pic, cap, ctx: ctx || null });

  Object.assign(P.CARDS, {
    // ---- risky ----
    hole: { by: 'dig',
      what: C(['......', '......', '......', '......', '###...', '#.###.', '#####.'], 'Empty cell, roofed over'),
      happens: C(['......', '......', '......', '......', '.OO...', '.OO.#.', '##.##.'], 'Piece over a gap'),
      avoid: C(['......', '......', '......', '......', '......', '.TTT#.', '##T##.'], 'Fill the gap first'),
      recover: C(['......', '......', 'I.....', 'I.....', 'I.....', 'I#####', '##.###'], 'Clear the row above') },
    overhang: { by: 'cleared',
      what: C(['......', '......', '......', '......', '###...', '#.....', '#####.'], 'Gap under a ledge'),
      happens: C(['......', '......', '......', '..OO..', '..OO..', '###...', '#####.'], 'Hanging past an edge'),
      avoid: C(['......', '......', '......', '......', '...OO.', '###OO.', '#####.'], 'Set it flat'),
      recover: C(['......', '......', '......', '......', '###...', '#IIII.', '#####.'], 'Slide a piece under') },
    pit: { by: 'cleared',
      what: C(['......', '......', '......', '##.##.', '##.##.', '##.##.', '#####.'], 'One wide, three deep'),
      happens: C(['......', '......', '...OO.', '##.OO.', '##.##.', '##.##.', '#####.'], 'Stacking beside a gap'),
      avoid: C(['......', '......', '..I...', '##I...', '##I##.', '##I##.', '#####.'], 'Fill it while shallow'),
      recover: C(['......', '......', '..I...', '##I##.', '##I##.', '##I##.', '#####.'], 'Drop an I in') },
    twoPits: { by: 'cleared',
      what: C(['......', '......', '......', '##.##.', '##.##.', '##.##.', '#####.'], 'Two pits, one I'),
      happens: C(['......', '......', '...OO.', '##.OO.', '##.##.', '##.##.', '#####.'], 'A second pit opens'),
      avoid: C(['......', '......', '..I...', '##I...', '##I##.', '##I##.', '#####.'], 'Keep just one well'),
      recover: C(['......', '......', '..I...', '##I##.', '##I##.', '##I##.', '#####.'], 'Fill one with I') },
    cliff: { by: 'cleared',
      what: C(['.......', '.......', '.......', '...###.', '...###.', '...###.', '######.'], 'Three-high step'),
      happens: C(['.......', '.......', '.......', '...OO..', '...OO..', '...###.', '######.'], 'Building one side up'),
      avoid: C(['.......', '.......', '.......', '.......', 'OO.....', 'OO.###.', '######.'], 'Raise the low side'),
      recover: C(['.......', '.......', '.......', '...###.', '..L###.', 'LLL###.', '######.'], 'Fill the low side') },
    rough: { by: 'cleared',
      what: C(['.......', '.......', '....#..', '....#..', '.#.##..', '.#.###.', '######.'], 'Many big steps'),
      happens: C(['....I..', '....I..', '....I..', '....I..', '....#..', '.#.###.', '######.'], 'Tower in the middle'),
      avoid: C(['.......', '.......', '.......', '.......', '.TTT#..', '.#T###.', '######.'], 'Fill a low spot'),
      recover: C(['.......', '.......', '..##...', '..##...', 'OO##...', 'OO##...', '######.'], 'Fill beside the bump') },
    noSZ: { by: 'cleared',
      what: C(['......', '......', '......', '......', '......', '#####.', '#####.'], 'No one-high step'),
      happens: C(['......', '......', '......', '......', '......', 'IIII#.', '#####.'], 'Leveling every step'),
      avoid: C(['......', '......', '......', '......', 'OO....', 'OO..#.', '#####.'], 'Keep one small step'),
      recover: C(['......', '......', '......', '..J...', '..JJJ.', '#####.', '#####.'], 'Make a small step') },
    coveredWell: { by: 'dig',
      what: C(['......', '......', '......', '###...', '##.###', '##.###', '##.###'], 'Roof over the well'),
      happens: C(['......', '......', '..OO..', '..OO..', '##.###', '##.###', '##.###'], 'Piece across the top'),
      avoid: C(['......', '......', '......', '..I...', '##I###', '##I###', '##I###'], 'Wait for the I'),
      recover: C(['......', '......', '.....L', '###LLL', '##.###', '##.###', '##.###'], 'Clear the roof row') },
    high: { by: 'cleared',
      what: C(['......', '#.....', '##....', '###...', '####..', '#####.', '#####.'], 'Top third reached'),
      happens: C(['......', 'OO....', 'OO....', '##....', '##....', '####..', '#####.'], 'Stacking with no clears'),
      avoid: C(['......', '......', '......', '##...I', '##...I', '####.I', '#####I'], 'Clear before it climbs'),
      recover: C(['......', '#.....', '##....', '###..I', '####.I', '#####I', '#####I'], 'Clear rows to drop') },
    spot: { by: 'room',
      what: C(['......', '......', '......', 'L...#.', 'L.#.#.', 'LL###.', '#####.'], 'O: no level pair'),
      happens: C(['......', '......', '.I....', '.I..#.', '.I#.#.', '.I###.', '#####.'], 'Tower on the pair'),
      avoid: C(['......', '......', '..S...', '..SS#.', '..#S#.', '..###.', '#####.'], 'Keep O a pair'),
      recover: C(['......', '......', '......', '#...#I', '#.#.#I', '#####I', '#####I'], 'Clear to level out') },
    nextPlan: { by: 'room', ctx: { visible: ['O', 'T', 'S'] },
      what: C(['......', '......', '......', 'L...#.', 'L.#.#.', 'LL###.', '#####.'], 'Next O: nowhere'),
      happens: C(['......', '......', '.I....', '.I..#.', '.I#.#.', '.I###.', '#####.'], 'Not looking at Next'),
      avoid: C(['......', '......', '..S...', '..SS#.', '..#S#.', '..###.', '#####.'], 'Leave room for Next'),
      recover: C(['......', '......', '......', '#...#I', '#.#.#I', '#####I', '#####I'], 'Make room, or Hold') },
    // ---- good ----
    flat: {
      what: C(['......', '......', '......', '......', '...##.', '#####.', '#####.'], 'Level, small steps'),
      happens: C(['......', '......', '......', '......', '.OO##.', '#OO##.', '#####.'], 'Fill the low pair'),
      avoid: C(['......', '.I....', '.I....', '.I....', '.I.##.', '#####.', '#####.'], 'A tall piece upright'),
      recover: C(['......', '......', '......', '......', 'OO###.', 'OO###.', '#####.'], 'Fill the low side') },
    slope: {
      what: C(['......', '......', '......', '...##.', '..###.', '.####.', '#####.'], 'Small steps, one way'),
      happens: C(['......', '......', '......', 'JJ....', 'J##...', 'J###..', '#####.'], 'Build up one side'),
      avoid: C(['......', '......', '......', '......', '#.OO..', '##OO..', '#####.'], 'A bump in it'),
      recover: C(['......', '......', '......', '....L.', '..LLL.', '.####.', '#####.'], 'Even out the top') },
    steps: {
      what: C(['......', '......', '......', '......', '......', '.#.##.', '#####.'], 'Steps both ways'),
      happens: C(['......', '......', '......', '#.Z#..', '#ZZ#..', '#Z###.', '#####.'], 'Leave one-high steps'),
      avoid: C(['......', '......', '......', '......', '#OO...', '#OO.#.', '#####.'], 'Leveling the steps'),
      recover: C(['......', '......', '......', '......', '..T...', '.TTT..', '#####.'], 'A T makes steps') },
    oFlat: {
      what: C(['......', '......', '......', '......', '..#...', '..#.#.', '#####.'], 'Two level columns'),
      happens: C(['......', '......', '......', '...#..', 'TTT#..', '#T###.', '#####.'], 'Make a level pair'),
      avoid: C(['......', '......', 'I.....', 'I.....', 'I.#...', 'I.#.#.', '#####.'], 'Breaking the only pair'),
      recover: C(['......', '......', '#I....', '#I....', '#I#...', '#I#.#.', '#####.'], 'Match a neighbour') },
    cleanWell: {
      what: C(['......', '......', '##....', '#####.', '#####.', '#####.', '#####.'], 'Four rows await I'),
      happens: C(['......', '......', '..J...', '##JJJ.', '#####.', '#####.', '#####.'], 'Finish the fourth row'),
      avoid: C(['......', '....OO', '##..OO', '#####.', '#####.', '#####.', '#####.'], 'Covering the well'),
      recover: C(['......', '......', '......', 'IIII#.', '#####.', '#####.', '#####.'], 'Fill rows, not well') },
    twistSlot: {
      what: C(['......', '......', '......', '..###.', '...##.', '#.###.', '#####.'], 'A T-shaped space'),
      happens: C(['......', '......', '...T..', '..TTT.', '...##.', '#.###.', '#####.'], 'Roof one side'),
      avoid: C(['......', '......', '.I....', '.I###.', '.I.##.', '#I###.', '#####.'], 'Filling it, no T'),
      recover: C(['......', '......', '...SS.', '..SS..', '...##.', '#.###.', '#####.'], 'Roof it again') },
    wellEdge: {
      what: C(['......', '......', '......', '#####.', '#####.', '#####.', '#####.'], 'Well against the wall'),
      happens: C(['......', '......', '......', '......', '#...L.', '##LLL.', '#####.'], 'Keep one side low'),
      avoid: C(['......', '......', '....OO', '....OO', '#####.', '#####.', '#####.'], 'Covering the well'),
      recover: C(['......', '......', '......', '....L.', '..LLL.', '#####.', '#####.'], 'Build up beside it') },
    burn: {
      what: C(['......', '......', '......', '#....I', '##...I', '####.I', '#####I'], 'One line when high'),
      happens: C(['......', '......', '.#....', 'I#....', 'I##...', 'I###..', 'I#####'], 'Take the small clear'),
      avoid: C(['......', '......', '......', '#.OO..', '##OO..', '####..', '#####.'], 'Stacking higher instead'),
      recover: C(['......', '......', '......', '#....I', '###..I', '#####I', '#####I'], 'Two lines, lower again') },
    bag: { ctx: { sinceI: 4, visible: ['S', 'O', 'T'] },
      what: C(['......', '......', '......', '##....', '#####.', '#####.', '#####.'], 'Well ready, I due'),
      happens: C(['......', '......', '......', '..J...', '##JJJ.', '#####.', '#####.'], 'Keep the well open'),
      avoid: C(['......', '......', '....OO', '##..OO', '#####.', '#####.', '#####.'], 'Giving up on I'),
      recover: C(['......', '......', '......', '....L.', '##LLL.', '#####.', '#####.'], 'Rebuild the ready rows') },
    holdGood: { ctx: { holdUsed: true, held: 'S' },
      what: C(['......', '......', '......', 'OO....', 'OO....', '#####.', '#####.'], 'Hold S, set O'),
      happens: C(['......', '......', '......', '..T...', '.TTT..', '#####.', '#####.'], 'No spot: hold it'),
      avoid: C(['......', '......', '......', '..SS..', '.SS...', '#####.', '#####.'], 'Forcing the S in', { holdUsed: false, held: null }),
      recover: C(['......', '......', '......', 'J.....', 'JJJ...', '#####.', '#####.'], 'Swap for a fit') },
    dig: {
      what: C(['......', '......', 'I.....', 'I.....', 'I.....', 'I#####', '##.###'], 'Clear above a hole'),
      happens: C(['......', '......', '.....I', '.....I', '.....I', '#####I', '###.##'], 'Dig down to it'),
      avoid: C(['......', '......', '......', 'OO....', 'OO....', '.#####', '##.###'], 'Burying it deeper'),
      recover: C(['......', '......', '.....I', '.....I', '.....I', '#####I', '####.#'], 'Clear, then fill it') },
    streak: { ctx: { streak: true },
      what: C(['......', '......', '......', '#####I', '#####I', '#####I', '#####I'], 'Quad after a Quad'),
      happens: C(['......', '......', '##....', '#####I', '#####I', '#####I', '#####I'], 'Another Quad'),
      avoid: C(['......', '......', '......', '.....I', '.....I', '.....I', '#####I'], 'A single breaks it', { streak: false }),
      recover: C(['......', '#.....', '##....', '#####I', '#####I', '#####I', '#####I'], 'Quads again') },
    combo: { ctx: { combo: 2 },
      what: C(['......', '......', '......', '......', '......', '####OO', '####OO'], 'Clears back to back'),
      happens: C(['......', '......', '......', '......', '.....J', '.....J', '####JJ'], 'Clear with each piece'),
      avoid: C(['......', '......', '......', '......', 'OO....', 'OO....', '####..'], 'A piece, no clear', { combo: 0 }),
      recover: C(['......', '......', '......', '......', '......', 'OO####', 'OO####'], 'Clear again next') },
    spotless: {
      what: C(['......', '......', '......', '......', '......', '####OO', '####OO'], 'Every cell cleared'),
      happens: C(['......', '......', '......', '#####I', '#####I', '#####I', '#####I'], 'Quad, nothing left'),
      avoid: C(['......', '......', '#.....', '#####I', '#####I', '#####I', '#####I'], 'Leftover cells stay'),
      recover: C(['......', '......', '......', '......', '......', '......', '##IIII'], 'Clear the last row') },
    // ---- combinations to avoid ----
    szFlat: { by: 'lines',
      what: C(['......', '......', '......', '..SS..', '.SS...', '#####.', '#####.'], 'S lying on flat'),
      happens: C(['......', '......', '......', 'ZZ....', '.ZZ...', '#####.', '#####.'], 'Z on level ground'),
      avoid: C(['......', '......', 'S.....', 'SS....', '#S....', '#####.', '#####.'], 'Stand it upright'),
      recover: C(['......', '......', '......', '..##.I', '.##..I', '#####I', '#####I'], 'Clear lines under it') },
    ljPit: { by: 'lines',
      what: C(['..J...', '..J...', '.JJ...', '##.##.', '##.##.', '##.##.', '#####.'], 'Foot catches the edge'),
      happens: C(['..L...', '..L...', '..LL..', '##.##.', '##.##.', '##.##.', '#####.'], 'L hooked on top'),
      avoid: C(['......', '......', '..I...', '##I##.', '##I##.', '##I##.', '#####.'], 'Only I goes in'),
      recover: C(['..#...', '..#...', '.##...', '##.##I', '##.##I', '##.##I', '#####I'], 'Clear down to it') },
    oUneven: { by: 'cleared:overhang',
      what: C(['......', '......', '......', '.OO...', '.OO...', '..###.', '#####.'], 'O across a step'),
      happens: C(['......', '......', '......', '..OO..', '..OO..', '...##.', '#####.'], 'Half on, half off'),
      avoid: C(['......', '......', '......', '......', 'OO....', 'OO###.', '#####.'], 'O on level ground'),
      recover: C(['......', '......', '......', 'L##...', 'L##...', 'LL###.', '#####.'], 'Tuck one under') },
    wellFill: { by: 'dig',
      what: C(['......', '......', '....OO', '....OO', '#####.', '#####.', '#####.'], 'O in the well'),
      happens: C(['......', '.....J', '.....J', '....JJ', '#####.', '#####.', '#####.'], 'J hooked over it'),
      avoid: C(['......', '......', '......', '.....I', '#####I', '#####I', '#####I'], 'Save it for I'),
      recover: C(['......', '......', '....#.', 'IIII##', '#####.', '#####.', '#####.'], 'Clear the cover row') },
    holdNoPlan: { by: 'holdGood', ctx: { holdUsed: true, held: 'O' },
      what: C(['......', '......', '......', '..SS..', '.SS...', '#####.', '#####.'], 'Held O fit here'),
      happens: C(['......', '......', '......', 'ZZ....', '.ZZ...', '#####.', '#####.'], 'Swapped for worse', { held: 'L' }),
      avoid: C(['......', '......', '......', 'OO....', 'OO....', '#####.', '#####.'], 'Set what fits', { holdUsed: false, held: null }),
      recover: C(['......', '......', '......', 'OO....', 'OO....', '#####.', '#####.'], 'Hold the misfit instead', { held: 'S' }) },
    // ---- advanced ----
    parity: { by: 'cleared',
      what: C(['......', '......', '......', '......', '..t...', '.ttt..', '#####.'], 'Checkerboard out of balance'),
      happens: C(['......', '......', '......', '......', '..T...', '.TTT..', '#####.'], 'T tips the balance'),
      avoid: C(['......', '......', '......', '......', '.T....', 'TTT...', '#####.'], 'T keeps it even'),
      recover: C(['......', '......', '......', '....T.', '..tTT.', '.tttT.', '#####.'], 'Another T, other way') },
    finesse: { by: 'none',
      what: C(['......', '......', '......', '......', 'OO....', 'OO....', '#####.'], 'Six keys, two needed', { keys: 6, minKeys: 2 }),
      happens: C(['......', '......', '......', '......', '..T...', '.TTT..', '#####.'], 'Turning the long way', { keys: 5, minKeys: 2 }),
      avoid: C(['......', '......', '......', '......', '..T...', '.TTT..', '#####.'], 'Turn the short way', { keys: 2, minKeys: 2 }),
      recover: C(['......', '......', '......', '......', 'OO....', 'OO....', '#####.'], 'Plan, then press', { keys: 3, minKeys: 2 }) },
    speed: { by: 'cleared', ctx: { level: 15 },
      what: C(['......', '......', '......', '##....', '#####.', '#####.', '#####.'], 'Fast and high'),
      happens: C(['......', '......', 'OO....', 'OO....', '#####.', '#####.', '#####.'], 'Building for a Quad'),
      avoid: C(['......', '......', '......', '.....I', '#####I', '#####I', '#####I'], 'Take lines early'),
      recover: C(['......', '......', '......', '##...I', '#####I', '#####I', '#####I'], 'Clear down fast') },
  });
})(typeof globalThis !== 'undefined' ? globalThis : this);
